version: "3.9"
services:

  wordpress:
    image: wordpress:${WORDPRESS_VERSION:-php7.4-fpm}
    container_name: wordpress-wordpress
    depends_on:
      - mysql
    environment:
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-wordpress}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD:-password}
    volumes:
      - ./config/php/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ${WORDPRESS_DIR:-./core/wordpress}:/var/www/html
    restart: always
    networks:
      - wordpress-network
      - youtube-api-external

  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: wordpress-mysql
    volumes:
      - ${MYSQL_DIR:-./core/mysql}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD:-no}
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD:-1}
    restart: always
    networks:
      - wordpress-network

  nginx:
    build:
      context: ./config/nginx
      args:
        - NGINX_IMAGE=nginx:${NGINX_VERSION:-latest}
        - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    container_name: wordpress-nginx
    depends_on:
      - wordpress
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
    volumes:
      - ${WORDPRESS_DIR:-./core/wordpress}:/var/www/html
      - ${NGINX_LOG_DIR:-./core/logs/nginx}:/var/log/nginx
    restart: always
    networks:
      - wordpress-network
      - youtube-api-external

volumes:
  mysql:
  wordpress:

networks:
  wordpress-network:
    driver: bridge
  youtube-api-external:
    external: true
    name: youtube-api-external
